#!/usr/bin/perl -w
=pod
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.
=cut



use strict;
use warnings;

my $sum = 0;
my $last = 1;

for(my $i = 1; $i < 4000000;){
	$i += $last;
	$last = $i - $last;
	if($i % 2 == 0){
		$sum += $i;
		}
	}
	
print "$sum";
